#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scopt_2.11
Version  : 4.0.0.rc2
Release  : 1
URL      : https://github.com/scopt/scopt/archive/v4.0.0-RC2.tar.gz
Source0  : https://github.com/scopt/scopt/archive/v4.0.0-RC2.tar.gz
Source1  : https://repo1.maven.org/maven2/com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.jar
Source2  : https://repo1.maven.org/maven2/com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-scopt_2.11-data = %{version}-%{release}
Requires: mvn-scopt_2.11-license = %{version}-%{release}

%description
[1]: http://scopt.github.io/scopt/3.5.0/api/index.html#scopt.OptionParser
# scopt
[![Maven Central](https://img.shields.io/maven-central/v/com.github.scopt/scopt_2.11.svg)](https://maven-badges.herokuapp.com/maven-central/com.github.scopt/scopt_2.11)
[![Javadocs](https://javadoc.io/badge/com.github.scopt/scopt_2.12.svg)](https://javadoc.io/doc/com.github.scopt/scopt_2.12)
[![Build Status](https://travis-ci.org/scopt/scopt.svg?branch=scopt3)](https://travis-ci.org/scopt/scopt)

%package data
Summary: data components for the mvn-scopt_2.11 package.
Group: Data

%description data
data components for the mvn-scopt_2.11 package.


%package license
Summary: license components for the mvn-scopt_2.11 package.
Group: Default

%description license
license components for the mvn-scopt_2.11 package.


%prep
%setup -q -n scopt-4.0.0-RC2

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-scopt_2.11
cp LICENSE.md %{buildroot}/usr/share/package-licenses/mvn-scopt_2.11/LICENSE.md
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/scopt/scopt_2.11/3.5.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/scopt/scopt_2.11/3.5.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.jar
/usr/share/java/.m2/repository/com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-scopt_2.11/LICENSE.md
